<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Job;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Senior Developer',
                'description' => 'Looking for a senior developer with experience in Laravel.',
                'location' => 'Remote',
                'salary' => 120000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '5+ years experience in PHP and Laravel.',
                'company_id' => 1,
                'category_id' => 1,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'senior',
                'remote_possible' => true,
            ],
            [
                'title' => 'Junior Developer',
                'description' => 'Entry-level developer with a passion for coding and learning.',
                'location' => 'New York, NY',
                'salary' => 60000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '1+ years experience with JavaScript and React.',
                'company_id' => 1,
                'category_id' => 2,
                'application_deadline' => now()->addDays(45),
                'experience_level' => 'junior',
                'remote_possible' => false,
            ],
            [
                'title' => 'Project Manager',
                'description' => 'Experienced project manager needed to lead development teams.',
                'location' => 'San Francisco, CA',
                'salary' => 90000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years of project management experience.',
                'company_id' => 1,
                'category_id' => 3,
                'application_deadline' => now()->addDays(60),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'UX/UI Designer',
                'description' => 'Creative designer with a strong portfolio in UI/UX.',
                'location' => 'Remote',
                'salary' => 70000.00,
                'job_type' => 'contract',
                'status' => 'open',
                'requirements' => '2+ years experience in UX/UI design.',
                'company_id' => 1,
                'category_id' => 4,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'mid',
                'remote_possible' => true,
            ],
            [
                'title' => 'Data Analyst',
                'description' => 'Analyze data and provide insights to improve business strategies.',
                'location' => 'Chicago, IL',
                'salary' => 80000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years experience with SQL and data analysis.',
                'company_id' => 1,
                'category_id' => 5,
                'application_deadline' => now()->addDays(15),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'DevOps Engineer',
                'description' => 'Responsible for deployment and network operations.',
                'location' => 'Remote',
                'salary' => 110000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '4+ years experience in DevOps.',
                'company_id' => 1,
                'category_id' => 6,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'senior',
                'remote_possible' => true,
            ],
            [
                'title' => 'Content Writer',
                'description' => 'Create and manage content for blogs and articles.',
                'location' => 'Austin, TX',
                'salary' => 50000.00,
                'job_type' => 'part-time',
                'status' => 'open',
                'requirements' => 'Excellent writing and research skills.',
                'company_id' => 1,
                'category_id' => 7,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'junior',
                'remote_possible' => true,
            ],
            [
                'title' => 'SEO Specialist',
                'description' => 'Optimize website content to rank higher in search engines.',
                'location' => 'Remote',
                'salary' => 65000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '2+ years experience in SEO.',
                'company_id' => 1,
                'category_id' => 8,
                'application_deadline' => now()->addDays(20),
                'experience_level' => 'mid',
                'remote_possible' => true,
            ],
            [
                'title' => 'Marketing Manager',
                'description' => 'Develop and execute marketing strategies.',
                'location' => 'Los Angeles, CA',
                'salary' => 90000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '5+ years experience in marketing.',
                'company_id' => 1,
                'category_id' => 9,
                'application_deadline' => now()->addDays(45),
                'experience_level' => 'senior',
                'remote_possible' => false,
            ],
            [
                'title' => 'HR Specialist',
                'description' => 'Manage recruitment, onboarding, and employee relations.',
                'location' => 'Remote',
                'salary' => 55000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '2+ years experience in HR.',
                'company_id' => 1,
                'category_id' => 10,
                'application_deadline' => now()->addDays(60),
                'experience_level' => 'mid',
                'remote_possible' => true,
            ],
            [
                'title' => 'Software Engineer',
                'description' => 'Design, develop, and test software applications.',
                'location' => 'Boston, MA',
                'salary' => 95000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years experience in software engineering.',
                'company_id' => 1,
                'category_id' => 7,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'Graphic Designer',
                'description' => 'Create visual concepts by hand or using software.',
                'location' => 'Remote',
                'salary' => 60000.00,
                'job_type' => 'contract',
                'status' => 'open',
                'requirements' => '2+ years experience in graphic design.',
                'company_id' => 1,
                'category_id' => 4,
                'application_deadline' => now()->addDays(15),
                'experience_level' => 'junior',
                'remote_possible' => true,
            ],
            [
                'title' => 'Business Analyst',
                'description' => 'Analyze business needs and provide solutions.',
                'location' => 'Seattle, WA',
                'salary' => 75000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years experience in business analysis.',
                'company_id' => 1,
                'category_id' => 10,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'Systems Administrator',
                'description' => 'Maintain and support IT systems and infrastructure.',
                'location' => 'Chicago, IL',
                'salary' => 70000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '2+ years experience in systems administration.',
                'company_id' => 1,
                'category_id' => 12,
                'application_deadline' => now()->addDays(45),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'Content Strategist',
                'description' => 'Plan and execute content strategies for various platforms.',
                'location' => 'Remote',
                'salary' => 68000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years experience in content strategy.',
                'company_id' => 1,
                'category_id' => 8,
                'application_deadline' => now()->addDays(20),
                'experience_level' => 'mid',
                'remote_possible' => true,
            ],
            [
                'title' => 'Product Manager',
                'description' => 'Oversee the development and delivery of products.',
                'location' => 'San Jose, CA',
                'salary' => 95000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '4+ years experience in product management.',
                'company_id' => 1,
                'category_id' => 10,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'senior',
                'remote_possible' => false,
            ],
            [
                'title' => 'Data Scientist',
                'description' => 'Analyze complex data to help drive business decisions.',
                'location' => 'Remote',
                'salary' => 105000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '5+ years experience in data science.',
                'company_id' => 1,
                'category_id' => 3,
                'application_deadline' => now()->addDays(45),
                'experience_level' => 'senior',
                'remote_possible' => true,
            ],
            [
                'title' => 'Network Engineer',
                'description' => 'Design, implement, and manage network solutions.',
                'location' => 'Dallas, TX',
                'salary' => 85000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '3+ years experience in network engineering.',
                'company_id' => 1,
                'category_id' => 5,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'mid',
                'remote_possible' => false,
            ],
            [
                'title' => 'Marketing Coordinator',
                'description' => 'Coordinate marketing campaigns and track their performance.',
                'location' => 'Remote',
                'salary' => 56000.00,
                'job_type' => 'full-time',
                'status' => 'open',
                'requirements' => '2+ years experience in marketing.',
                'company_id' => 1,
                'category_id' => 10,
                'application_deadline' => now()->addDays(30),
                'experience_level' => 'junior',
                'remote_possible' => true,
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}
